name: Build and Push Docker Image for tgolshop

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Create env file
      run: |
        echo "DB_URL=${{ secrets.DB_URL }}" >> .env.production
        echo "SECRET_CODE=${{ secrets.SECRET_CODE }}" >> .env.production
      
    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/golf-market:latest .
      
    - name: Push Docker Image to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/golf-market:latest
